### ISSUE TITLE
[BUG] "mai nap gomb" kitakarja az időpontot

### ISSUE THREAD

**Issue by Foglaltnev** [domedav/Neptun-2#10]
**Milyen problémát tapasztalsz?**
Órarendnél a kis házikó gomb ki tudja takarni hosszú nap esetén az utolsó óra időpontját.

**Mit csináltál a probléma előhívásához?**
Részletes leírás hogyan lehet replikálni a problémát
1. Rögtön megnyitás után 

[Screenshot_2024-02-21-20-04-23-400_com domedav neptun2](https://github.com/domedav/Neptun-2/assets/160778292/29f3d248-234d-4ce2-8eec-c7de94b82d75)

**Comment by domedav** [comment]
Ezt jó, hogy jelezted!

Kövi release-be fixelve lesz, a kis "home" gombot lehet majd mozgatni!😁
