### ISSUE TITLE
Új neptun 2fa

### ISSUE THREAD

**Issue by Mark7888** [domedav/Neptun-2#13]
A neptun bevezette az egyetemünkön (Pannon Egyetem) a 2 lépcsős hitelesítést (Google Authenticator, Microsoft Authenticator, stb használatával), és azóta, valószínűleg emiatt nem tölt be semmit az alkalmazás.

![Screenshot_20240417-144908.png](https://github.com/domedav/Neptun-2/assets/44124704/f2bebbcf-5c2f-4156-8796-cad5f49d78cf)

**Comment by domedav** [comment]
Igen, tisztában vagyok ezzel a problémával, mivel énis Pannonos vagyok.
Viszont nem tudok mit csinálni ezzel, hiszen a Neptun2 a mobilos neptun app API-ra épül, ami nem támogatja a 2fa-t.

**Comment by domedav** [comment]
A nyár folyamán meglesz csinálva valamikor.
