### ISSUE TITLE
Statikus a hetek szamozasa

### ISSUE THREAD

**Issue by rcmdkick** [domedav/Neptun-2#14]
Hello!
Az en egyetemem az energia valsag miatt mindig kesobb kezdodik es vegzodnek a felevek. Ezert eppen ebben a pillanatban nalunk 10. Het, mig az applikacioban 11.het van.

Lehetseges e, hogy pl egy beiratkozasi idoszaktol szamolja, vagy esetleg egy "offset" beallitast beletenni?

(Kepet felesleges csatolnom, az app irja h 11.het apr.15-19)

Elore is koszi, ha megoldhato!

**Comment by domedav** [comment]
Ezt jó, hogy jelzed, amint lesz időm, megcsinálom.
