### ISSUE TITLE
[IDEA] English language support

### ISSUE THREAD

**Issue by heyitsazar** [domedav/Neptun-2#19]
Dear dev, thanks for the application! I wonder how can I help you for translating this application. I can help translating the app in English, Azerbaijani and Turkish.

**Comment by domedav** [comment]
Multiple language support wasnt really planned, but I will be doing a codebase rewrite during the summer anyways, so I will add multiple language support.

The translation to Azerbaijani and Turkish would be much appreciated!

**Comment by domedav** [comment]
Language support have finally been added.

[Language Resources - EN](https://github.com/user-attachments/files/15595992/neptun2.txt)
If you could help me with translation, I'd appreciate it so much.

**Comment by heyitsazar** [comment]
Great! I will work on it as soon as possible.
