### ISSUE TITLE
[IDEA] Olvasatlan üzenetek

### ISSUE THREAD

**Issue by RedyAu** [domedav/Neptun-2#20]
Az app láthatóan tudja, melyek az olvasatlan üzenetek, és olvasottnak is jelöli őket megnyitáskor.
Elsőként király lenne, ha az olvasatlanoknál lenne egy pötty vagy hasonló, az olvasottaknál pedig levehetné a félkövért az üzenet címéről.

Valamint király lenne egy összes olvasottnak jelölése funkció.

**Comment by domedav** [comment]
A postaládás emoji mindenképpen marad, viszont a félkövér eltüntetése az olvasottnál jó ötlet. Kövi frissítésbe benne is lesz.

**Comment by RedyAu** [comment]
Oh ha ez eddig is volt, akkor annyira nem volt feltűnő, hogy keresve se találtam 😅
Köszi az appot!

**Comment by RedyAu** [comment]
Látom, elkészült, viszont szerintem még így is könnyen össze lehet téveszteni az olvasott és olvasatlan leveleket.
Javaslom vagy nagyobbra venni a weight-különbséget (az olvasott levelek nem semibold, hanem akár thin lehetnek).
Akár enyhe háttérszínt is kaphatnának az olvasatlanok?

**Comment by domedav** [comment]
Az új verzióba módosítottam 1-2 dolgot ezzel kapcsolatosan, szerintem elég látható lett így már melyik az amelyik nincs elolvasva.

Viszont valamikor majd csinálok szűrési illetve keresési lehetőséget a levelekhez.

**Comment by RedyAu** [comment]
Okés, köszi! Akkor ez zárható.
