### ISSUE TITLE
Bejelentkezés

### ISSUE THREAD

**Issue by liliszitas** [domedav/Neptun-2#4]
Nem tudok bejelentkezni a neptun kóddal es a jelszavammal, valamiert hibát ir ki :)

**Comment by domedav** [comment]
Nézd meg, hogy jó iskolába akarsz-e bejelentkezni, és a bejelenzkezési adataid is ugyan azok, mint amit a webes neptunban használsz.

Ha minden jó, és mégis hibát ír, tudnál képernyőképeket adni a problémáról?
Illetve, hogy melyik egyetemről van szó.

**Comment by domedav** [comment]
Próbáld meg eggyel régebbi verzióval a bejelentkezést. Ha úgysem jó, akkor fogalmam sincs mi miatt lehet. Utánnanézek a problémának jobban.

**Comment by liliszitas** [comment]
Rendben, köszönöm ☺️

**Comment by liliszitas** [comment]
Kikapcsoltam, és így sikerült, köszönöm :D 
Eszembe nem jutott volna hogy amiatt lehet
