### ISSUE TITLE
Hiányzó egyetem

### ISSUE THREAD

**Issue by rantotthusforever** [domedav/Neptun-2#5]
Nem található a listán az egyetem ahová járok (Magyar Agrár- és Élettudományi Egyetem). 
Várható valamikor a felkerülése? 
Előre is köszi a választ. :)

**Comment by domedav** [comment]
Valószínűleg ez azért van, mert nincs a központi neptun rendszerbe az iskolád neptun URL-je felvéve.
Majd a következő verzióba lehetséges lesz az URL-t is megadni, kiválasztás helyett.
