### ISSUE TITLE
[BUG] orarend

### ISSUE THREAD

**Issue by rcmdkick** [domedav/Neptun-2#6]
**Milyen problémát tapasztalsz?**
Elállitott orarend (24. Hetre rakja a febr. 12-16-ot).

**Mit csináltál a probléma előhívásához?**
1.  Megnyitom az appot.
2. Az orarend menujet behivva maris megjelenik.

**Képernyőképek**
![Screenshot_20240217_223734.jpg](https://github.com/domedav/Neptun-2/assets/23213414/9333f513-7975-47bf-b643-55b265eda294)

**Comment by rcmdkick** [comment]
Illetve a vasarnap szo el van irva 😄

**Comment by B3nec** [comment]
> Illetve a vasarnap szo el van irva 😄

That's a feature, not a bug 😂

**Comment by domedav** [comment]
órarend kicsit átlesz dolgozva majd a kövi frissítésekbe 💪🏻
