### ISSUE TITLE
[Bug] Befizetendok

### ISSUE THREAD

**Issue by rcmdkick** [domedav/Neptun-2#7]
befizetendo menupont 2 osregi (asszem torolt) bejegyzest mutat.![Screenshot_20240217_224041.jpg](https://github.com/domedav/Neptun-2/assets/23213414/f92bcf7c-35df-4078-aa8b-6888da56b36e)

**Comment by domedav** [comment]
ezzel szerintem nem tudok mit csinálni ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by rcmdkick** [comment]
Mi alapjan jelenitesz / tuntetsz el valamilyen tetelt?

**Comment by domedav** [comment]
időkorlát alapján működik az egész, mer kb az az egyetlen adat amit visszaad az api, és ilyenre lehet használni

**Comment by rcmdkick** [comment]
Hmm, ez segit? ![Screenshot_20240220_104520_Chrome.jpg](https://github.com/domedav/Neptun-2/assets/23213414/9c105704-2aea-40de-8115-e414e2df08a1)

**Comment by domedav** [comment]
aha 🤍

kövi updatebe lesz is fix 💪🏻
