### ISSUE TITLE
[Bug] fura idoszakok

### ISSUE THREAD

**Issue by rcmdkick** [domedav/Neptun-2#9]
idoszakoknal nem ismeri fel a felevet (1. Felevet ir), ezen kivul mas idoszaki bejegyzeseket is latnia kene nalunk.

**Comment by rcmdkick** [comment]
![Screenshot_20240217_224048.jpg](https://github.com/domedav/Neptun-2/assets/23213414/91610f2f-b01e-4025-a3cf-6d4e258ec857)

**Comment by domedav** [comment]
Kössz, hogy mondod, ez a bug javítás alatt van. 💪🏻

**Comment by domedav** [comment]
Tudnál adni képet, hogy milyen időszakok vannak neked a webes neptunban

**Comment by rcmdkick** [comment]
![Screenshot_20240302_002505_Chrome.jpg](https://github.com/domedav/Neptun-2/assets/23213414/4c280864-3f32-43e7-ad2e-adb7cf20158e)
